/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RestParkingSpot

/**
 * 
 * @param id Identifiant unique du parking
 * @param name Nom du parking
 * @param location Emplacement du parking
 * @param spots Liste des places de parking disponibles dans ce parking
 * @param available Nombre de places actuellement disponibles dans ce parking
 */
data class RestParking (

    /* Identifiant unique du parking */
    val id: kotlin.String,
    /* Nom du parking */
    val name: kotlin.String,
    /* Emplacement du parking */
    val location: kotlin.String? = null,
    /* Liste des places de parking disponibles dans ce parking */
    val spots: kotlin.Array<RestParkingSpot>,
    /* Nombre de places actuellement disponibles dans ce parking */
    val available: kotlin.Int
) {
}