/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RestSpotStatus

/**
 * 
 * @param number Numéro unique de la place de parking
 * @param status 
 * @param licensePlate Numéro de plaque d'immatriculation du véhicule
 * @param arrivalTime Date et heure d'arrivée du véhicule
 */
data class RestParkingSpot (

    /* Numéro unique de la place de parking */
    val number: kotlin.Int,
    val status: RestSpotStatus,
    /* Numéro de plaque d'immatriculation du véhicule */
    val licensePlate: kotlin.String? = null,
    /* Date et heure d'arrivée du véhicule */
    val arrivalTime: kotlin.String? = null
) {
}