/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param licensePlate Numéro de plaque d'immatriculation du véhicule
 */
data class RestBookParkingSpotRequest (

    /* Numéro de plaque d'immatriculation du véhicule */
    val licensePlate: kotlin.String
) {
}