/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name Nom du parking
 * @param location Emplacement du parking
 * @param spotsNumber Nombre de places de parking disponibles dans ce parking
 */
data class RestNewParking (

    /* Nom du parking */
    val name: kotlin.String,
    /* Emplacement du parking */
    val location: kotlin.String? = null,
    /* Nombre de places de parking disponibles dans ce parking */
    val spotsNumber: kotlin.Int
) {
}