/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RestParking

/**
 * 
 * @param total Nombre total de parkings
 * @param parkings Liste des parkings
 */
data class RestParkings (

    /* Nombre total de parkings */
    val total: kotlin.Int,
    /* Liste des parkings */
    val parkings: kotlin.Array<RestParking>
) {
}