/**
 * Gestion de places de parking API
 * API pour gérer les places de parking
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Statut de la place de parking
 * Values: FREE,OCCUPIED
 */
enum class RestSpotStatus(val value: kotlin.String){
    FREE("FREE"),// :/
    OCCUPIED("OCCUPIED");// :/
}